// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2018-08-20 13:39:00.493158729 -0500 CDT m=+1.501271712

package docs

import (
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "description": "\u003cupdate description\u003e",
        "title": "go-microservice-1",
        "contact": {
            "name": "\u003cupdate contact name\u003e"
        },
        "license": {},
        "version": "1.0"
    },
    "paths": {
        "/": {
            "get": {
                "description": "If this endpoint does not work, something is seriously busted",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "basic"
                ],
                "summary": "Greets you with a friendly message",
                "responses": {
                    "200": {
                        "description": "The service was able to start enough to be able to service inbound requests",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/rye.JSONStatus"
                        }
                    }
                }
            }
        },
        "/docs/index.html": {
            "get": {
                "description": "This endpoint serves the API spec via Swagger-UI (using github.com/swaggo/swag)",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "basic"
                ],
                "summary": "View API docs via Swagger-UI",
                "responses": {
                    "200": {
                        "description": "Swagger-UI",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Describes the current health of fleet-api",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "basic"
                ],
                "summary": "Describes the current health of fleet-api",
                "responses": {
                    "200": {
                        "description": "All is well",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.HealthcheckStatus"
                        }
                    },
                    "500": {
                        "description": "The service is unhealthy",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.HealthcheckStatus"
                        }
                    }
                }
            }
        },
        "/version": {
            "get": {
                "description": "Another simple handler, similar to '/' - if this does not work, something is broken",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "basic"
                ],
                "summary": "Returns the current version of the service",
                "responses": {
                    "200": {
                        "description": "'status' contains the string 'version', while 'message' will contain the actual version",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/rye.JSONStatus"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.HealthcheckStatus": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "object"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "rye.JSONStatus": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        }
    }
}`

type s struct{}

func (s *s) ReadDoc() string {
	return doc
}
func init() {
	swag.Register(swag.Name, &s{})
}
